production:
  environment: production
  production_environment: true
  required_contexts: ["build_and_test"]

staging:
  environment: staging
  production_environment: false
  required_contexts: ["build_and_test"]
