# - name: disable default site
#   file:
#     path: /etc/nginx/conf.d/default.conf
#     state: absent

- name: create app conf.d
  template:
    src: iicanada-prod.conf.j2
    dest: /etc/nginx/conf.d/iicanada-prod.conf
    mode: 0644

- name: enable nginx
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: restarted
