language: elixir
elixir: '1.7.4'
otp_release: '21.1'

env:
  - DB_PASS=""

cache:
  directories:
    - _build
    - deps

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$PATH:$HOME/.cargo/bin
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get

before_script:
  - ./reset_db_local.sh test

script:
  - ./compile_and_test.sh
