version: "3.7"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    # volumes:
    #   - ".docker/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
