env: flex
runtime: gs://elixir-runtime/elixir-2019-01-19-000446.yaml
runtime_config:
  release_app: volunteer
  packages:
    - rustc
  build:
    - "cd assets && npm config set \"@fortawesome:registry\" https://npm.fontawesome.com/9CE01F9A-101C-4F60-84F1-83F8ABC92500 && NODE_ENV=development npm install && npm run production && cd .. && mix phx.digest"

skip_files:
  - "_build"
  - ".git"
  - ".vagrant"
  - "assets/node_modules"
  - "deps"
  - "passwords"
  - "priv/commands/node_modules"
  - "priv/statuc"
  - "assets/node_modules"
  - "test"

env_variables:
  DB_USER: postgres
  DB_PASS: kJOrj2pe6rICEnEB
  DB_NAME: postgres
  DB_HOST: /cloudsql/ismailivolunteer-201223:northamerica-northeast1:prod-ismailivolunteer/.s.PGSQL.5432
  NODE_ENV: production

beta_settings:
  cloud_sql_instances: ismailivolunteer-201223:northamerica-northeast1:prod-ismailivolunteer

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6
