env: flex
runtime: gs://elixir-runtime/elixir-2019-07-18-112708.yaml
runtime_config:
  release_app: volunteer
  packages:
    - rustc
  build:
    - "cd assets && npm config set \"@fortawesome:registry\" <%= font_awesome.registry %> && NODE_ENV=development npm install && npm run production && cd .. && mix phx.digest"
    - "cd priv/commands && NODE_ENV=production npm install"

skip_files:
  - "_build"
  - ".git"
  - ".vagrant"
  - "assets/node_modules"
  - "deps"
  - "infra"
  - "priv/static"
  - "priv/commands/node_modules"
  - "sync"
  - "test"

env_variables:
<%= for {key, value} <- env do %>
  <%= key %>: "<%= value %>"
<% end %>

beta_settings:
  cloud_sql_instances: "ismailivolunteer-201223:northamerica-northeast1:<%= db.gcloud_id %>"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6
