env: flex
runtime: gs://elixir-runtime/elixir-2019-10-29-183530.yaml
entrypoint: /app/lib/volunteer-2.0.0/priv/startup.sh
runtime_config:
  release_app: volunteer
  packages:
    - rustc
  build:
    - 'cd assets && npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && npm config set "//npm.fontawesome.com/:_authToken" <%= font_awesome.auth_token %> && NODE_ENV=development npm install && npm run production && cd .. && mix phx.digest'
    - 'cd priv/commands && NODE_ENV=production npm install'

skip_files:
  - "_build"
  - "deps"
  - ".git"
  - "infra"
  - "assets/node_modules"
  - "priv/commands/node_modules"
  - "priv/static"
  - "test"

env_variables:
<%= for {key, value} <- envvars do %>
  <%= key %>: '<%= value %>'
<% end %>

beta_settings:
  cloud_sql_instances: "ismailivolunteer-201223:northamerica-northeast1:<%= db.gcloud_id %>"

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.6
