- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'
    validate: 'visudo -cf %s'
