- name: install ufw
  apt:
    name: ufw
    state: latest
    update_cache: yes

- name: reset all rules
  ufw:
    state: reset

- name: limit ssh connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: allow port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: allow port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: defaultly allow all outgoing connections
  ufw:
    direction: outgoing
    default: allow

- name: defaultly deny all incoming connections
  ufw:
    direction: incoming
    default: deny

- name: enable ufw
  ufw:
    state: enabled
    logging: on
