- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - unattended-upgrades
    - apt-listchanges
    # - update-notifier

- name: copy 10periodic file
  copy:
    dest: /etc/apt/apt.conf.d/10periodic
    force: yes
    src: 10periodic

- name: email results to root
  lineinfile:
    backup: yes
    create: no
    regexp: '^Unattended-Upgrade::Mail'
    line: 'Unattended-Upgrade::Mail: "root";'
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present

- name: enable automatic reboot
  lineinfile:
    backup: yes
    create: no
    regexp: '^Unattended-Upgrade::Automatic-Reboot'
    line: 'Unattended-Upgrade::Automatic-Reboot: "true";'
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
