- name: create the deployment user
  user:
    name: deploy
    password: "{{ global_deploy_password }}"
    shell: /bin/bash
    groups: sudo
    system: yes
    state: present

- name: set authorized key from file for the deployment user
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', global_deploy_public_key) }}"
