- import_tasks: manage/include_global_vars.yaml

- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - mailutils
    - libsasl2-modules
    - postfix

- name: change to localhost only
  lineinfile:
    backup: yes
    create: no
    regexp: "^inet_interfaces"
    line: inet_interfaces = localhost
    path: /etc/postfix/main.cf
    state: present

- name: restart postfix
  systemd:
    name: postfix
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: forward to correct email address
  lineinfile:
    backup: yes
    create: no
    regexp: "^root"
    line: "root: {{ forwarding_email_address }}"
    path: /etc/aliases
    state: present

- name: reload aliases
  command: newaliases
