- name: update base packages
  apt:
    only_upgrade: yes
    install_recommends: yes
    autoremove: yes
    state: latest
    update_cache: yes
    upgrade: yes

- name: install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - chrony
    - tzdata
    - htop
    - wget
    - unzip
    - vim

- import_tasks: setup_time.yaml
- import_tasks: setup_locale.yaml
- import_tasks: swapfile.yaml
- import_tasks: mount_data_volume.yaml
