- hosts: all
  become: yes
  become_user: root

  roles:

    - init
    - postgres

  tasks:

    - name: install local id_rsa keyfile
      tags: [ "vagrant" ]
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
        user: vagrant

    - name: download erlang dpkg
      tags: [ "vagrant" ]
      get_url:
        url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        dest: ~/

    - name: install erlang dpkg
      tags: [ "vagrant" ]
      shell: dpkg -i ~/erlang-solutions_1.0_all.deb

    - name: add nodejs repo
      tags: [ "vagrant" ]
      shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

    - name: install required packages
      tags: [ "vagrant" ]
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - elixir
        - esl-erlang
        - nodejs
