- hosts: all
  become: yes
  become_user: root

  roles:

    - init
    - postgres

  tasks:

    - name: change postgres authentication method to trust all local logins
      tags: [ "vagrant" ]
      lineinfile:
        backup: yes
        create: no
        insertafter: IPv4\slocal\sconnections
        line: host    all             all             all                     trust
        path: /etc/postgresql/10/main/pg_hba.conf
        state: present

    - name: re-enable postgres@10-main service
      tags: [ "vagrant" ]
      systemd:
        name: postgresql@10-main
        enabled: yes
        state: restarted

    - name: install local id_rsa keyfile
      tags: [ "vagrant" ]
      authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
        user: vagrant

    - name: download erlang dpkg
      tags: [ "vagrant" ]
      get_url:
        url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        dest: ~/

    - name: install erlang dpkg
      tags: [ "vagrant" ]
      shell: dpkg -i ~/erlang-solutions_1.0_all.deb

    - name: add nodejs repo
      tags: [ "vagrant" ]
      shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

    - name: install required packages
      tags: [ "vagrant" ]
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - elixir
        - esl-erlang
        - nodejs
