name:                     BuildTestDeploy

on:                       [push]

jobs:
  build:

    runs-on:              ubuntu-latest

    steps:

      - uses:             actions/checkout@v1

      - name:             Setup Elixir
        uses:             actions/setup-elixir@1.0.0
        with:
          elixir-version: 1.8.2
          otp-version:    21.3
          install-hex:    true
          install-rebar:  true

      - name:             Setup PostgreSQL
        uses:                   Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version:   "9.6"
          postgresql db:        "postgres_test"
          postgresql user:      "postgres"
          postgresql password:  "postgres"

      - name:             Decrypt Secrets
        run:              "./infra-decrypt.sh"
        env:
          INFRA_GPG_PASS: ${{ secrets.INFRA_GPG_PASS }}

      - name:             Test
        run:              "./compile_and_test.sh"

      - name:             Deploy to Production
        run:              "./deploy.sh prod"

      - name:             Cache `_build` folder
        uses:             actions/cache@v1
        with:
          path:           "./_build"
          key:            ${{ runner.os }}-${{ hashFiles('./mix.lock') }}

      - name:             Cache `deps` folder
        uses:             actions/cache@v1
        with:
          path:           "./deps"
          key:            ${{ runner.os }}-${{ hashFiles('./mix.lock') }}
