name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Elixir
      uses: actions/setup-elixir@1.0.0
      with:
        elixir-version: 1.8.2
        otp-version: 21.3
        install-hex: true
        install-rebar: true
    - name: Install Google Cloud Platform (GCP) CLI
      run: "apt-get install gcp"
    - name: Deploy to Production
      run: "./deploy prod"
